name: simbio
channels:
  - conda-forge
dependencies:
  - numpy >= 1.14
  - pandas >= 1
  - scipy
  - numba
  - typing_extensions
  - matplotlib
  - pre-commit
  - pytest
  - typer
  - jupyer-book
  - jupytext
  - pip
  - pip:
    - poincare
